// Generated by CoffeeScript 1.8.0
(function() {
  var buildBoard;

  buildBoard = function() {
    return [0, 1, 2, 3].map(function() {
      return [0, 1, 2, 3].map(function() {
        return 0;
      });
    });
  };

  console.log(superPower([30, 20, 3, 4, 5]));

}).call(this);

//# sourceMappingURL=game.js.map
