// Generated by CoffeeScript 1.8.0
(function() {
  var buildBoard, generateTile, generateTileValue, printArray, randomCellIndices, randomInt;

  randomInt = function(x) {
    return Math.floor(Math.random() * x);
  };

  randomCellIndices = function() {
    return [randomInt(4), randomInt(4)];
  };

  buildBoard = function() {
    return [0, 1, 2, 3].map(function() {
      return [0, 1, 2, 3].map(function() {
        return 0;
      });
    });
  };

  generateTileValue = function() {
    var tileValue;
    tileValue = randomInt(5);
    if (tileValue < 4) {
      tileValue = 2;
    } else {
      tileValue = 4;
    }
    return tileValue;
  };

  generateTile = function(board) {
    var col, row, tileValue, _ref;
    _ref = randomCellIndices(), row = _ref[0], col = _ref[1];
    tileValue = generateTileValue();
    if (board[row][col] === 0) {
      board[row][col] = tileValue;
    } else {
      generateTile(board);
      console.log("Reset tile generation");
    }
    return console.log(board);
  };

  printArray = function(array) {
    var row, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      row = array[_i];
      _results.push(console.log(row));
    }
    return _results;
  };

  $(function() {
    var board;
    board = buildBoard();
    generateTile(board);
    generateTile(board);
    return printArray(board);
  });

}).call(this);

//# sourceMappingURL=main.js.map
